# Default values for snmpexporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: prom/snmp-exporter
  version: v0.17.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80